### ISSUE TITLE
Robust04_DPH_KL.res

### ISSUE THREAD

**Issue by wangxinzhe123** [zh-zheng/BERT-QE#2]
您好，请问Robust04_DPH_KL.res文件具体是什么格式的？方便给一个模板吗？谢谢

**Comment by zh-zheng** [comment]
这是用于`trec_eval`评价脚本的格式，具体可以参考：http://faculty.washington.edu/levow/courses/ling573_SPR2011/hw/trec_eval_desc.htm

**Comment by wangxinzhe123** [comment]
不好意思，关于Robust04_DPH_KL.res文件我还是不太清楚，请问方便给我一份您的文件吗
