### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/content/drive/MyDrive/BERT-QE-master/disk4/FT/FT943'

### ISSUE THREAD

**Issue by wangxinzhe123** [zh-zheng/BERT-QE#3]
请问，robust04_preprocess.py第100行的语句：pool.map(preprocess, files)：我的理解files是robust数据集下的文件的路径,，例如/content/drive/MyDrive/BERT-QE-master/disk4/FT/FT911/FT911_1，但是preprocess函数中f_out = open(os.path.join(robust04_output_path, path.split("/")[-1].split(".gz")[0]), 'w')
    f = gzip.open(path, 'rt', encoding='utf8', errors='ignore')却是以gzip文件的格式打开，不知道我的理解出了什么问题？

**Comment by zh-zheng** [comment]
Hi,
`files`是原始的robust04数据集下的文件路径列表，每个路径都对应一个gz文件。一个示例路径为：`/your_path/robust04/disk4/CR/CR93H119.gz`
如果你的数据已经解压，则直接`open`即可。

**Comment by wangxinzhe123** [comment]
非常感谢您的回答
