### ISSUE TITLE
qrels file

### ISSUE THREAD

**Issue by wangxinzhe123** [zh-zheng/BERT-QE#4]
不好意思再次打扰您，请问run.sh中的qrels_file=${main_path}/${dataset}/qrels ，qrels文件从哪里获取？

**Comment by zh-zheng** [comment]
可在README的[Data preparation](https://github.com/zh-zheng/BERT-QE#data-preparation)一节中获取。
qrels文件：https://trec.nist.gov/data/robust/qrels.robust2004.txt

**Comment by wangxinzhe123** [comment]
NotFoundError: /content/drive/MyDrive/BERT-QE-master/robust04/passage/large/query_passage_ids.txt; No such file or directory请问select_pieces.py中138行：ids_file_path = os.path.join(path, "query_{}_ids{}.txt".format(FLAGS.task, suffix))没有query_passage_ids.txt这个文件

**Comment by zh-zheng** [comment]
你是否按照README的说明运行了`run.sh`？具体的说，你是否运行了`convert_tfrecord.py`？

**Comment by wangxinzhe123** [comment]
不好意思，是我运行时候的问题，非常感谢您的回复
