### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by wangxinzhe123** [zh-zheng/BERT-QE#5]
valueError: Couldn't find 'checkpoint' file or checkpoints in given directory
请问checkpoint文件要怎么下载和使用呢，我下载了uncased_L-24_H-1024_A-16和BERT-Small文件，可他依然提醒我 Couldn't find 'checkpoint' file or checkpoints in given directory

**Comment by zh-zheng** [comment]
请下载[这里](https://github.com/zh-zheng/BERT-QE#resources)的checkpoint，并按照README中的说明将checkpoint放在合适的位置。如果仍有疑问，请贴出你的代码片段和具体的报错信息。
